export const starters: Array<string> = [
    'Fine let me have a look.',
    'Let\'s see what u got!',
    'Ugh... here we go again',
    'If I must...',
    'Haha. Are you a masochist or something?',
    'Let\'s see... :thinking:',
    'Haha are you sure about that?',
    'Fine I\'ll take a look.',
    'Oh boy this is going to be funny.',
    'Here I go again...',
    'Why do I even bother? ...',
    'Oh yay I wonder what im gonna find :unamused:',
    'I have 0 expectations about this... ',
    'I\'ve already made up my mind you know... ',
    'I guess you like being humiliated',
    'I have a strong feeling your taste sucks',
    '3..2..1.. your waifu is trash. Knew that even before looking. :stuck_out_tongue:',
    'Ugh I\'m gonna need a diving suit for this...',
    'I\'m gonna need a diving suit aren\'t I?',
    'I fully expect this to be bad...',
    'If I do this will you leave me alone?',
    'You again... just why'
]

export const judging: Array<string> = [
    'Oh this doesn\'t look good at all...',
    'Just as I thought... :rolling_eyes:',
    'You degenerate...',
    'The degeneracy...',
    'This is making me sick',
    'Wow this is bad',
    'Wow this sucks :joy:',
    'Hahahahahahahahahaha :joy:',
    'This list is rich :joy:',
    'Were you always a burden to society?',
    'Being able to put together so much trash is almost admirable...',
    'I definitely was right to think your waifu was trash.',
    'I knew your waifu was trash...',
    'I was expecting something bad but this...',
    'Your waifu is trash.',
    'Your waifu is definitely trash.',
    'Really? Is this for real? :joy:',
    'Haha this is so embarassing',
    'Do you consider yourself a grown-up? Just wondering :joy:',
    'I hate you for making me go through this',
    'Why did I accept this?',
    'This is bad...'
]